name: Changeset Workflow

permissions:
  contents: write
  actions: write

on:
  push:
    branches:
      - pipe
  workflow_dispatch:

jobs:
  changeset:
    runs-on: ubuntu-latest
    steps:
      - name: Teste de mudanças
        run: echo "Mudanças processadas com sucesso!"
