name: Deploy Workflow

on:
  workflow_run:
    workflows: ["Changeset Workflow"]
    types:
      - success

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy bem-sucedido
        run: echo "Deploy bem-sucedido após changeset!"
